blank_issues_enabled: false
contact_links:
  - name: âœ Documentation improvement
    about: Please open the PR instead!
    url: https://github.com/Meqn/pipflow/pulls
  - name: âœ¨ Feature Request / idea
    url: https://github.com/Meqn/pipflow/discussions/new
    about: Missing something in MobX? Let us know.
  - name: ğŸ’¬ Question / Discussion
    about: Feel free to ask anything.
    url: https://github.com/Meqn/pipflow/discussions/new
  - name: ğŸ“– View documentation
    url: https://pipflow.mengqing.org
    about: Official pipflow documentation.